// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9uBwpK70ZfGI8eH7bXB9rAQD5SC2Mc9w',
    appId: '1:520396323634:android:ef6717795fd55838bfb52b',
    messagingSenderId: '520396323634',
    projectId: 'heal-v-app',
    storageBucket: 'heal-v-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnuzOiPIGInniMacj70cS3zP2KIIL9rE0',
    appId: '1:520396323634:ios:0200485bdf80d2dcbfb52b',
    messagingSenderId: '520396323634',
    projectId: 'heal-v-app',
    storageBucket: 'heal-v-app.firebasestorage.app',
    androidClientId: '520396323634-619rfvmmdh6ri8kj4sfurn8vnvl4dga6.apps.googleusercontent.com',
    iosClientId: '520396323634-bl3fbrn4kls5je6j3fp609n6phf60h82.apps.googleusercontent.com',
    iosBundleId: 'com.healv',
  );
}
